apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ze6gr6jzm-python
  janus-idp.io/tekton: ze6gr6jzm-python
  backstage.io/kubernetes-id: ze6gr6jzm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ze6gr6jzm-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
