apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ze6gr6jzm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ze6gr6jzm-python 
  name: ze6gr6jzm-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ze6gr6jzm-python
    weight: 100 
