apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ze6gr6jzm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ze6gr6jzm-python 
  name: ze6gr6jzm-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ze6gr6jzm-python 
