apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ze6gr6jzm-python-gitops
  description: This is GitOps manifest for ze6gr6jzm-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ze6gr6jzm-python
    backstage.io/kubernetes-id: ze6gr6jzm-python 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/ze6gr6jzm-python-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ze6gr6jzm-python
